namespace: wazo
name: zoiper-oem-plugin
description: This plugin integrates Zoiper OEM QR generation into Wazo.
version: 0.0.1
plugin_format_version: 1
depends:
  - name: admin-ui-context
    namespace: official
debian_depends:
  - curl

